ARG PHP_BASE=local/krayin-crm:deps-partial
FROM ${PHP_BASE}

RUN apt-get update \
    && apt-get install -y --no-install-recommends libpq-dev \
    && docker-php-ext-install pdo_pgsql \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src/php
